### ISSUE TITLE
Result of queries for "Ability" seems outdated

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.DataProvider#201]
https://planetariumhq.slack.com/archives/C03P5080KJL/p1660291051994619

https://app.asana.com/0/1133453747809944/1202781624201481

**Comment by area363** [comment]
This turned out to be a non-issue because the report was based on an internal test, in which the `Ability Ranking` is actually not provided.

Ref: https://app.asana.com/0/0/1202781624201481/1202802491488408/f

**Comment by area363** [comment]
Reopening this issue because the level in ability ranking is being updated late.

**Comment by area363** [comment]
The level was displaying incorrectly because the backup data-provider node was updating the avatar info in the past blocks. The backup node has been modified to not update the avatar info.
