### ISSUE TITLE
Slow action execution

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.DataProvider#225]
History

8/23: 다른 RPC 노드 대비로 2배 이상 느린 상황
8/29: 추가 조사된 것 없음, 데이터 확인 후 이슈화

**Comment by area363** [comment]
10/13:
* https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=Data-Provider Created a cloudwatch dashboard for `Data-Provider` services.
* Test async query version

**Comment by area363** [comment]
Slow execution resolved after https://github.com/planetarium/NineChronicles.DataProvider/pull/268 for now.
