### ISSUE TITLE
Skip saving failed adventure boss action

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.DataProvider#730]
Currently, DP saves failed action (especially claim action).
Change to skip failed actions.

**Comment by U-lis** [comment]
음.. 근데 이건 좀 봤는데 초반 몇개 말고는 실패한 action 이 안 들어가 있는 것 같은...데... 좀 더 봐야 할 듯...

**Comment by ipdae** [comment]
- 조사 필요 (실패한건이 실제 성공 테이블에 기록이 되는지 봐야함)

**Comment by U-lis** [comment]
제보 받고 확인해봤을 때 adventure boss 처음 만들었을 때 5개?10개? 정도 실패한 action 이 성공 table 에 기록되어 있는걸 확인했는데
간간이 한번씩 최근 table 기록을 봤을 때는 극초반 이후로는 기록된 것이 없는 것으로 보임.
지속적으로 추적이 필요.
