### ISSUE TITLE
Create db migration tool from RocksDB to MySQL

### ISSUE THREAD

**Issue by area363** [planetarium/NineChronicles.DataProvider#766]
Currently, adding data to MySQL from Block 0 takes too long (over 1M blocks at this point). Therefore, a migration tool is needed to move pre-existing RocksDB data to MySQL.

**Comment by moreal** [comment]
@area363 I transferred this issue here from lib9c because it seems related with this repository. If this issue is not needed anymore, please close this issue 🙏🏻

**Comment by area363** [comment]
Thanks! Yes this one is very outdated and no longer needed 😅
